# Generated by Django 4.1 on 2023-09-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cartapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="card_id",
            new_name="cart_id",
        ),
    ]
